local inter_clr = Color(60, 60, 60)
local red_clr = Color(220, 60, 60)
local blue_clr = Color(60, 60, 220)
team.SetUp(1, "Intermission", inter_clr, false)
team.SetUp(2, "Red", red_clr, false)
team.SetUp(3, "Blue", blue_clr, false)
